export default dummyData = {
	'Living Room': {
		categories: {
			Seating: [
				'Sofas',
				'Sectionals',
				'Sofette Sectionals',
				'Sofette',
				'Armchairs',
				'Stools',
				'Ottoman',
				'Poufs',
				'Sofas',
				'Sectionals',
				'Sofette Sectionals',
				'Sofette',
				'Armchairs',
				'Stools',
				'Ottoman',
				'Poufs',
				'Sofas',
				'Sectionals',
				'Sofette Sectionals',
				'Sofette',
			],
			Tables: [
				'Chairs',
				'Stools',
				'Coffee Tables',
				'Indoor Benches',
				'Console Tables',
				'Gaming Chairs',
				'Writing Desks',
				'Secretary Desks',
				'Console Tables',
				'Gaming Chairs',
				'Writing Desks',
				'Secretary Desks',
			],
			Storage: [
				'Bookcases',
				'Tv Cabinets',
				'Highboards',
				'Display Cabinets',
				'Hallway units',
				'Wall mounted units',
				'Bookcases',
				'Tv Cabinets',
				'Highboards',
				'Display Cabinets',
				'Hallway units',
				'Wall mounted units',
			],
			Decor: [
				'Sofas',
				'Sectionals',
				'Sofette Sectionals',
				'Sofette',
				'Armchairs',
				'Stools',
				'Ottoman',
				'Poufs',
				'Sofas',
				'Sectionals',
				'Sofette Sectionals',
				'Sofette',
				'Armchairs',
				'Stools',
				'Ottoman',
				'Poufs',
				'Sofas',
				'Sectionals',
				'Sofette Sectionals',
				'Sofette',
			],
		},
	},
};
